// <auto-generated />
using CookiClickerEF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CookiClickerEF.Migrations
{
    [DbContext(typeof(CookieClickerContext))]
    [Migration("20180616103439_Add money system to models")]
    partial class Addmoneysystemtomodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("CookiClickerEF.Models.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Money");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameStateUpgrade", b =>
                {
                    b.Property<int>("UpgradeId");

                    b.Property<int>("GameStateId");

                    b.Property<int>("Amount");

                    b.HasKey("UpgradeId", "GameStateId");

                    b.HasIndex("GameStateId");

                    b.ToTable("GameUpgrade");
                });

            modelBuilder.Entity("CookiClickerEF.Models.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DependencyId");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.ToTable("Upgrade");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameState", b =>
                {
                    b.HasOne("CookiClickerEF.Models.GameState", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameStateUpgrade", b =>
                {
                    b.HasOne("CookiClickerEF.Models.GameState", "GameState")
                        .WithMany("GameStateUpgrades")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookiClickerEF.Models.Upgrade", "Upgrade")
                        .WithMany("GameStateUpgrades")
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookiClickerEF.Models.Upgrade", b =>
                {
                    b.HasOne("CookiClickerEF.Models.Upgrade", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId");
                });
#pragma warning restore 612, 618
        }
    }
}
