// <auto-generated />
using System;
using CookiClickerEF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookiClickerEF.Migrations
{
    [DbContext(typeof(CookieClickerContext))]
    [Migration("20180617201831_Add new columns")]
    partial class Addnewcolumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("CookiClickerEF.Models.GameStateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Money");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameStateUpgradeData", b =>
                {
                    b.Property<int>("UpgradeId");

                    b.Property<int>("GameStateId");

                    b.Property<int>("Amount");

                    b.HasKey("UpgradeId", "GameStateId");

                    b.HasIndex("GameStateId");

                    b.ToTable("GameUpgrade");
                });

            modelBuilder.Entity("CookiClickerEF.Models.UpgradeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveAddition");

                    b.Property<int?>("DependencyId");

                    b.Property<string>("FileName");

                    b.Property<string>("Name");

                    b.Property<int>("PassiveAddition");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.ToTable("Upgrade");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameStateData", b =>
                {
                    b.HasOne("CookiClickerEF.Models.GameStateData", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("CookiClickerEF.Models.GameStateUpgradeData", b =>
                {
                    b.HasOne("CookiClickerEF.Models.GameStateData", "GameState")
                        .WithMany("GameStateUpgrades")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookiClickerEF.Models.UpgradeData", "Upgrade")
                        .WithMany("GameStateUpgrades")
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookiClickerEF.Models.UpgradeData", b =>
                {
                    b.HasOne("CookiClickerEF.Models.UpgradeData", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId");
                });
#pragma warning restore 612, 618
        }
    }
}
